In [26]:
import pandas as pd

In [27]:
dados = pd.read_json('/content/dados_hospedagem.json')

In [28]:
dados = pd.json_normalize(dados['info_moveis'])

In [29]:
colunas = list(dados.columns)
colunas

['avaliacao_geral',
 'comodidades',
 'descricao_local',
 'descricao_vizinhanca',
 'experiencia_local',
 'max_hospedes',
 'modelo_cama',
 'preco',
 'quantidade_banheiros',
 'quantidade_camas',
 'quantidade_quartos',
 'taxa_deposito',
 'taxa_limpeza']

In [39]:
colunas_lista = []
colunas_nao_lista = []

for col in dados.columns:
    # Find the first non-null value in the column
    first_non_null = dados[col].dropna().iloc[0] if not dados[col].dropna().empty else None

    if isinstance(first_non_null, list):
        colunas_lista.append(col)
    else:
        colunas_nao_lista.append(col)

print("Colunas com valores de lista:", colunas_lista)
print("Colunas com valores não-lista:", colunas_nao_lista)

Colunas com valores de lista: ['comodidades', 'descricao_local', 'descricao_vizinhanca', 'modelo_cama', 'preco', 'quantidade_banheiros', 'quantidade_camas', 'quantidade_quartos', 'taxa_deposito', 'taxa_limpeza']
Colunas com valores não-lista: ['avaliacao_geral', 'experiencia_local', 'max_hospedes']

In [40]:
dados = dados[colunas_nao_lista + colunas_lista]
print("DataFrame reordered successfully. New column order:")
print(dados.columns.tolist())

DataFrame reordered successfully. New column order:
['avaliacao_geral', 'experiencia_local', 'max_hospedes', 'comodidades', 'descricao_local', 'descricao_vizinhanca', 'modelo_cama', 'preco', 'quantidade_banheiros', 'quantidade_camas', 'quantidade_quartos', 'taxa_deposito', 'taxa_limpeza']

In [41]:
colunas = list(dados.columns)
colunas

['avaliacao_geral',
 'experiencia_local',
 'max_hospedes',
 'comodidades',
 'descricao_local',
 'descricao_vizinhanca',
 'modelo_cama',
 'preco',
 'quantidade_banheiros',
 'quantidade_camas',
 'quantidade_quartos',
 'taxa_deposito',
 'taxa_limpeza']

In [42]:
dados_novos = dados.explode(colunas[3:])
dados_novos.head()

,avaliacao_geral,experiencia_local,max_hospedes,comodidades,descricao_local,descricao_vizinhanca,modelo_cama,preco,quantidade_banheiros,quantidade_camas,quantidade_quartos,taxa_deposito,taxa_limpeza
0,10.0,--,1,"{Internet,""Wireless Internet"",Kitchen,""Free Pa...",This clean and comfortable one bedroom sits ri...,Lower Queen Anne is near the Seattle Center (s...,Real Bed,$110.00,1,1,1,$0,$0
0,10.0,--,1,"{TV,Internet,""Wireless Internet"",Kitchen,""Free...",Our century old Upper Queen Anne house is loca...,"Upper Queen Anne is a really pleasant, unique ...",Futon,$45.00,1,1,1,$0,$0
0,10.0,--,1,"{TV,Internet,""Wireless Internet"",Kitchen,""Free...",Cozy room in two-bedroom apartment along the l...,The convenience of being in Seattle but on the...,Futon,$55.00,1,1,1,$0,$0
0,10.0,--,1,"{Internet,""Wireless Internet"",Kitchen,""Free Pa...",Very lovely and cozy room for one. Convenientl...,"Ballard is lovely, vibrant and one of the most...",Pull-out Sofa,$52.00,1,1,1,$0,$20.00
0,10.0,--,1,"{""Wireless Internet"",Kitchen,""Free Parking on ...",The “Studio at Mibbett Hollow' is in a Beautif...,--,Real Bed,$85.00,1,1,1,$0,$15.00

In [43]:
dados_novos.reset_index(inplace=True, drop=True)
dados_novos.head()

,avaliacao_geral,experiencia_local,max_hospedes,comodidades,descricao_local,descricao_vizinhanca,modelo_cama,preco,quantidade_banheiros,quantidade_camas,quantidade_quartos,taxa_deposito,taxa_limpeza
0,10.0,--,1,"{Internet,""Wireless Internet"",Kitchen,""Free Pa...",This clean and comfortable one bedroom sits ri...,Lower Queen Anne is near the Seattle Center (s...,Real Bed,$110.00,1,1,1,$0,$0
1,10.0,--,1,"{TV,Internet,""Wireless Internet"",Kitchen,""Free...",Our century old Upper Queen Anne house is loca...,"Upper Queen Anne is a really pleasant, unique ...",Futon,$45.00,1,1,1,$0,$0
2,10.0,--,1,"{TV,Internet,""Wireless Internet"",Kitchen,""Free...",Cozy room in two-bedroom apartment along the l...,The convenience of being in Seattle but on the...,Futon,$55.00,1,1,1,$0,$0
3,10.0,--,1,"{Internet,""Wireless Internet"",Kitchen,""Free Pa...",Very lovely and cozy room for one. Convenientl...,"Ballard is lovely, vibrant and one of the most...",Pull-out Sofa,$52.00,1,1,1,$0,$20.00
4,10.0,--,1,"{""Wireless Internet"",Kitchen,""Free Parking on ...",The “Studio at Mibbett Hollow' is in a Beautif...,--,Real Bed,$85.00,1,1,1,$0,$15.00

In [44]:
dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 70 entries, 0 to 69
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   avaliacao_geral       70 non-null     object
 1   experiencia_local     70 non-null     object
 2   max_hospedes          70 non-null     object
 3   comodidades           70 non-null     object
 4   descricao_local       70 non-null     object
 5   descricao_vizinhanca  70 non-null     object
 6   modelo_cama           70 non-null     object
 7   preco                 70 non-null     object
 8   quantidade_banheiros  70 non-null     object
 9   quantidade_camas      70 non-null     object
 10  quantidade_quartos    70 non-null     object
 11  taxa_deposito         70 non-null     object
 12  taxa_limpeza          70 non-null     object
dtypes: object(13)
memory usage: 7.2+ KB

In [45]:
import numpy as np

In [54]:
dados_novos['max_hospedes'] = dados_novos['max_hospedes'].astype(np.int64)

In [48]:
dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 70 entries, 0 to 69
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   avaliacao_geral       70 non-null     object
 1   experiencia_local     70 non-null     object
 2   max_hospedes          70 non-null     int64
 3   comodidades           70 non-null     object
 4   descricao_local       70 non-null     object
 5   descricao_vizinhanca  70 non-null     object
 6   modelo_cama           70 non-null     object
 7   preco                 70 non-null     object
 8   quantidade_banheiros  70 non-null     object
 9   quantidade_camas      70 non-null     object
 10  quantidade_quartos    70 non-null     object
 11  taxa_deposito         70 non-null     object
 12  taxa_limpeza          70 non-null     object
dtypes: int64(1), object(12)
memory usage: 7.2+ KB

In [49]:
col_numericas = ['quantidade_banheiros', 'quantidade_quartos', 'quantidade_camas']

In [52]:
dados_novos[col_numericas] = dados_novos[col_numericas].astype(np.int64)

In [55]:
dados_novos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3818 entries, 0 to 3817
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   avaliacao_geral       3818 non-null   object
 1   experiencia_local     3818 non-null   object
 2   max_hospedes          3818 non-null   int64
 3   comodidades           3818 non-null   object
 4   descricao_local       3818 non-null   object
 5   descricao_vizinhanca  3818 non-null   object
 6   modelo_cama           3818 non-null   object
 7   preco                 3818 non-null   object
 8   quantidade_banheiros  3818 non-null   int64
 9   quantidade_camas      3818 non-null   int64
 10  quantidade_quartos    3818 non-null   int64
 11  taxa_deposito         3818 non-null   object
 12  taxa_limpeza          3818 non-null   object
dtypes: int64(4), object(9)
memory usage: 387.9+ KB

In [56]:
dados_novos['avaliacao_geral'] = dados_novos['avaliacao_geral'].astype(np.float64)

In [57]:
dados_novos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3818 entries, 0 to 3817
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   avaliacao_geral       3162 non-null   float64
 1   experiencia_local     3818 non-null   object
 2   max_hospedes          3818 non-null   int64
 3   comodidades           3818 non-null   object
 4   descricao_local       3818 non-null   object
 5   descricao_vizinhanca  3818 non-null   object
 6   modelo_cama           3818 non-null   object
 7   preco                 3818 non-null   object
 8   quantidade_banheiros  3818 non-null   int64
 9   quantidade_camas      3818 non-null   int64
 10  quantidade_quartos    3818 non-null   int64
 11  taxa_deposito         3818 non-null   object
 12  taxa_limpeza          3818 non-null   object
dtypes: float64(1), int64(4), object(8)
memory usage: 387.9+ KB

In [65]:
dados_novos['precos'] = dados_novos['preco'].apply(lambda x: x.replace('$', '').replace(',', '').strip())

In [66]:
dados_novos['precos'] = dados_novos['precos'].astype(np.float64)

In [67]:
dados_novos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3818 entries, 0 to 3817
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   avaliacao_geral       3162 non-null   float64
 1   experiencia_local     3818 non-null   object
 2   max_hospedes          3818 non-null   int64
 3   comodidades           3818 non-null   object
 4   descricao_local       3818 non-null   object
 5   descricao_vizinhanca  3818 non-null   object
 6   modelo_cama           3818 non-null   object
 7   preco                 3818 non-null   object
 8   quantidade_banheiros  3818 non-null   int64
 9   quantidade_camas      3818 non-null   int64
 10  quantidade_quartos    3818 non-null   int64
 11  taxa_deposito         3818 non-null   object
 12  taxa_limpeza          3818 non-null   object
 13  precos                3818 non-null   float64
dtypes: float64(2), int64(4), object(8)
memory usage: 417.7+ KB

In [71]:
dados_novos[['taxa_deposito', 'taxa_limpeza']] = dados_novos[['taxa_deposito', 'taxa_limpeza']].applymap(lambda x: x.replace('$', '').replace(',', '').strip())

/tmp/ipython-input-2607063985.py:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  dados_novos[['taxa_deposito', 'taxa_limpeza']] = dados_novos[['taxa_deposito', 'taxa_limpeza']].applymap(lambda x: x.replace('$', '').replace(',', '').strip())

In [72]:
dados_novos[['taxa_deposito', 'taxa_limpeza']] = dados_novos[['taxa_deposito', 'taxa_limpeza']].astype(np.float64)

In [73]:
dados_novos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3818 entries, 0 to 3817
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   avaliacao_geral       3162 non-null   float64
 1   experiencia_local     3818 non-null   object
 2   max_hospedes          3818 non-null   int64
 3   comodidades           3818 non-null   object
 4   descricao_local       3818 non-null   object
 5   descricao_vizinhanca  3818 non-null   object
 6   modelo_cama           3818 non-null   object
 7   preco                 3818 non-null   object
 8   quantidade_banheiros  3818 non-null   int64
 9   quantidade_camas      3818 non-null   int64
 10  quantidade_quartos    3818 non-null   int64
 11  taxa_deposito         3818 non-null   float64
 12  taxa_limpeza          3818 non-null   float64
 13  precos                3818 non-null   float64
dtypes: float64(4), int64(4), object(6)
memory usage: 417.7+ KB

In [76]:
dados_novos['descricao_local'] = dados_novos['descricao_local'].str.lower()

In [78]:
dados_novos['descricao_local'][3169]

"built, run and supported by seattle tech and start up veterans, grokhome's focus is to create a supportive environment for smart people working on interesting projects, start ups and more. this listing is an upper bunk, in a 2-person shared room. *note: this fall, there will be major renovations happening on one kitchen and bathroom at a time. there will always be two other working kitchens and two working bathrooms in the house. we'll work to minimize the impact these renovations have on your stay. **this listing is only available to those working in the tech/science space. live in a hacker house, and immerse yourself in the seattle tech scene. you can expect to be surrounded by smart people solving big problems or working on something fun. we have frequent demo nights, and love when our guests share something they are passionate about. if you're new to the city, our deep ties to the seattle tech scene can help you get involved. expand your network, develop your ideas, and learn somet"

In [83]:
dados_novos['descricao_local'] = dados_novos['descricao_local'].str.replace('[^a-zA-Z0-9\-\']',' ',regex=True)

<>:1: SyntaxWarning: invalid escape sequence '\-'
<>:1: SyntaxWarning: invalid escape sequence '\-'
/tmp/ipython-input-3317589037.py:1: SyntaxWarning: invalid escape sequence '\-'
  dados_novos['descricao_local'] = dados_novos['descricao_local'].str.replace('[^a-zA-Z0-9\-\']',' ',regex=True)

In [85]:
dados_novos['descricao_local'] = dados_novos['descricao_local'].str.replace('(?<!\w)-(?!\w)',' ',regex=True)

<>:1: SyntaxWarning: invalid escape sequence '\w'
<>:1: SyntaxWarning: invalid escape sequence '\w'
/tmp/ipython-input-3233522736.py:1: SyntaxWarning: invalid escape sequence '\w'
  dados_novos['descricao_local'] = dados_novos['descricao_local'].str.replace('(?<!\w)-(?!\w)',' ',regex=True)

In [89]:
dados_novos['descricao_local'] = dados_novos['descricao_local'].str.split()

In [91]:
dados_novos.head()

,avaliacao_geral,experiencia_local,max_hospedes,comodidades,descricao_local,descricao_vizinhanca,modelo_cama,preco,quantidade_banheiros,quantidade_camas,quantidade_quartos,taxa_deposito,taxa_limpeza,precos
0,10.0,--,1,"{Internet,""Wireless Internet"",Kitchen,""Free Pa...","[this, clean, and, comfortable, one, bedroom, ...",Lower Queen Anne is near the Seattle Center (s...,Real Bed,$110.00,1,1,1,0.0,0.0,110.0
1,10.0,--,1,"{TV,Internet,""Wireless Internet"",Kitchen,""Free...","[our, century, old, upper, queen, anne, house,...","Upper Queen Anne is a really pleasant, unique ...",Futon,$45.00,1,1,1,0.0,0.0,45.0
2,10.0,--,1,"{TV,Internet,""Wireless Internet"",Kitchen,""Free...","[cozy, room, in, two-bedroom, apartment, along...",The convenience of being in Seattle but on the...,Futon,$55.00,1,1,1,0.0,0.0,55.0
3,10.0,--,1,"{Internet,""Wireless Internet"",Kitchen,""Free Pa...","[very, lovely, and, cozy, room, for, one, conv...","Ballard is lovely, vibrant and one of the most...",Pull-out Sofa,$52.00,1,1,1,0.0,20.0,52.0
4,10.0,--,1,"{""Wireless Internet"",Kitchen,""Free Parking on ...","[the, studio, at, mibbett, hollow', is, in, a,...",--,Real Bed,$85.00,1,1,1,0.0,15.0,85.0

In [92]:
dados_novos['comodidades'] = dados_novos['comodidades'].str.replace('\{|}|\"','',regex=True)

<>:1: SyntaxWarning: invalid escape sequence '\{'
<>:1: SyntaxWarning: invalid escape sequence '\{'
/tmp/ipython-input-300044671.py:1: SyntaxWarning: invalid escape sequence '\{'
  dados_novos['comodidades'] = dados_novos['comodidades'].str.replace('\{|}|\"','',regex=True)

In [94]:
dados_novos['comodidades'] = dados_novos['comodidades'].str.split(',')

In [95]:
dados_novos.head()

,avaliacao_geral,experiencia_local,max_hospedes,comodidades,descricao_local,descricao_vizinhanca,modelo_cama,preco,quantidade_banheiros,quantidade_camas,quantidade_quartos,taxa_deposito,taxa_limpeza,precos
0,10.0,--,1,"[Internet, Wireless Internet, Kitchen, Free Pa...","[this, clean, and, comfortable, one, bedroom, ...",Lower Queen Anne is near the Seattle Center (s...,Real Bed,$110.00,1,1,1,0.0,0.0,110.0
1,10.0,--,1,"[TV, Internet, Wireless Internet, Kitchen, Fre...","[our, century, old, upper, queen, anne, house,...","Upper Queen Anne is a really pleasant, unique ...",Futon,$45.00,1,1,1,0.0,0.0,45.0
2,10.0,--,1,"[TV, Internet, Wireless Internet, Kitchen, Fre...","[cozy, room, in, two-bedroom, apartment, along...",The convenience of being in Seattle but on the...,Futon,$55.00,1,1,1,0.0,0.0,55.0
3,10.0,--,1,"[Internet, Wireless Internet, Kitchen, Free Pa...","[very, lovely, and, cozy, room, for, one, conv...","Ballard is lovely, vibrant and one of the most...",Pull-out Sofa,$52.00,1,1,1,0.0,20.0,52.0
4,10.0,--,1,"[Wireless Internet, Kitchen, Free Parking on P...","[the, studio, at, mibbett, hollow', is, in, a,...",--,Real Bed,$85.00,1,1,1,0.0,15.0,85.0

In [96]:
dados_novos['descricao_vizinhanca'] = dados_novos['descricao_vizinhanca'].str.replace('[^a-zA-Z0-9\-\']',' ',regex=True)

<>:1: SyntaxWarning: invalid escape sequence '\-'
<>:1: SyntaxWarning: invalid escape sequence '\-'
/tmp/ipython-input-4196095265.py:1: SyntaxWarning: invalid escape sequence '\-'
  dados_novos['descricao_vizinhanca'] = dados_novos['descricao_vizinhanca'].str.replace('[^a-zA-Z0-9\-\']',' ',regex=True)

In [97]:
dados_novos['descricao_vizinhanca'] = dados_novos['descricao_vizinhanca'].str.replace('(?<!\w)-(?!\w)',' ',regex=True)

<>:1: SyntaxWarning: invalid escape sequence '\w'
<>:1: SyntaxWarning: invalid escape sequence '\w'
/tmp/ipython-input-3090885627.py:1: SyntaxWarning: invalid escape sequence '\w'
  dados_novos['descricao_vizinhanca'] = dados_novos['descricao_vizinhanca'].str.replace('(?<!\w)-(?!\w)',' ',regex=True)

In [98]:
dados_novos['descricao_vizinhanca'] = dados_novos['descricao_vizinhanca'].str.split()

In [99]:
dados_novos.head()

,avaliacao_geral,experiencia_local,max_hospedes,comodidades,descricao_local,descricao_vizinhanca,modelo_cama,preco,quantidade_banheiros,quantidade_camas,quantidade_quartos,taxa_deposito,taxa_limpeza,precos
0,10.0,--,1,"[Internet, Wireless Internet, Kitchen, Free Pa...","[this, clean, and, comfortable, one, bedroom, ...","[Lower, Queen, Anne, is, near, the, Seattle, C...",Real Bed,$110.00,1,1,1,0.0,0.0,110.0
1,10.0,--,1,"[TV, Internet, Wireless Internet, Kitchen, Fre...","[our, century, old, upper, queen, anne, house,...","[Upper, Queen, Anne, is, a, really, pleasant, ...",Futon,$45.00,1,1,1,0.0,0.0,45.0
2,10.0,--,1,"[TV, Internet, Wireless Internet, Kitchen, Fre...","[cozy, room, in, two-bedroom, apartment, along...","[The, convenience, of, being, in, Seattle, but...",Futon,$55.00,1,1,1,0.0,0.0,55.0
3,10.0,--,1,"[Internet, Wireless Internet, Kitchen, Free Pa...","[very, lovely, and, cozy, room, for, one, conv...","[Ballard, is, lovely, vibrant, and, one, of, t...",Pull-out Sofa,$52.00,1,1,1,0.0,20.0,52.0
4,10.0,--,1,"[Wireless Internet, Kitchen, Free Parking on P...","[the, studio, at, mibbett, hollow', is, in, a,...",[],Real Bed,$85.00,1,1,1,0.0,15.0,85.0