<a href="https://colab.research.google.com/github/dobsfoxx/ETL-Pandas-ONE-Alura/blob/main/Exercicio_convers%C3%A3o_de_valores_metodo(replace_strip).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import pandas as pd

In [11]:
dados = pd.read_json('dados_vendas_clientes.json')

In [12]:
dados = pd.json_normalize(dados['dados_vendas'])

In [13]:
dados

,Cliente,Data de venda,Valor da compra
0,"[@ANA _LUCIA 321, DieGO ARMANDIU 210, DieGO AR...",06/06/2022,"[R$ 836,5, R$ 573,33, R$ 392,8, R$ 512,34]"
1,"[Isabely JOanes 738, Isabely JOanes 738, Isabe...",07/06/2022,"[R$ 825,31, R$ 168,07, R$ 339,18, R$ 314,69]"
2,"[Isabely JOanes 738, JOãO Gabriel 671, Julya m...",08/06/2022,"[R$ 682,05, R$ 386,34, R$ 622,65, R$ 630,79]"
3,"[Julya meireles 914, MaRIA Julia 444, MaRIA Ju...",09/06/2022,"[R$ 390,3, R$ 759,16, R$ 334,47, R$ 678,78]"
4,"[MaRIA Julia 444, PEDRO PASCO 812, Paulo castr...",10/06/2022,"[R$ 314,24, R$ 311,15, R$ 899,16, R$ 885,24]"

In [14]:
colunas = list(dados.columns)
colunas

['Cliente', 'Data de venda', 'Valor da compra']

In [15]:
dados= dados.explode(colunas[2])

In [16]:
dados

,Cliente,Data de venda,Valor da compra
0,"[@ANA _LUCIA 321, DieGO ARMANDIU 210, DieGO AR...",06/06/2022,"R$ 836,5"
0,"[@ANA _LUCIA 321, DieGO ARMANDIU 210, DieGO AR...",06/06/2022,"R$ 573,33"
0,"[@ANA _LUCIA 321, DieGO ARMANDIU 210, DieGO AR...",06/06/2022,"R$ 392,8"
0,"[@ANA _LUCIA 321, DieGO ARMANDIU 210, DieGO AR...",06/06/2022,"R$ 512,34"
1,"[Isabely JOanes 738, Isabely JOanes 738, Isabe...",07/06/2022,"R$ 825,31"
1,"[Isabely JOanes 738, Isabely JOanes 738, Isabe...",07/06/2022,"R$ 168,07"
1,"[Isabely JOanes 738, Isabely JOanes 738, Isabe...",07/06/2022,"R$ 339,18"
1,"[Isabely JOanes 738, Isabely JOanes 738, Isabe...",07/06/2022,"R$ 314,69"
2,"[Isabely JOanes 738, JOãO Gabriel 671, Julya m...",08/06/2022,"R$ 682,05"
2,"[Isabely JOanes 738, JOãO Gabriel 671, Julya m...",08/06/2022,"R$ 386,34"
2,"[Isabely JOanes 738, JOãO Gabriel 671, Julya m...",08/06/2022,"R$ 622,65"
2,"[Isabely JOanes 738, JOãO Gabriel 671, Julya m...",08/06/2022,"R$ 630,79"
3,"[Julya meireles 914, MaRIA Julia 444, MaRIA Ju...",09/06/2022,"R$ 390,3"
3,"[Julya meireles 914, MaRIA Julia 444, MaRIA Ju...",09/06/2022,"R$ 759,16"
3,"[Julya meireles 914, MaRIA Julia 444, MaRIA Ju...",09/06/2022,"R$ 334,47"
3,"[Julya meireles 914, MaRIA Julia 444, MaRIA Ju...",09/06/2022,"R$ 678,78"
4,"[MaRIA Julia 444, PEDRO PASCO 812, Paulo castr...",10/06/2022,"R$ 314,24"
4,"[MaRIA Julia 444, PEDRO PASCO 812, Paulo castr...",10/06/2022,"R$ 311,15"
4,"[MaRIA Julia 444, PEDRO PASCO 812, Paulo castr...",10/06/2022,"R$ 899,16"
4,"[MaRIA Julia 444, PEDRO PASCO 812, Paulo castr...",10/06/2022,"R$ 885,24"

In [17]:
dados['Valor da compra'] = dados['Valor da compra'].apply(lambda x: x.replace('R$', '').replace('reais', '').replace(',','.').strip()).astype(np.float64)

In [18]:
dados.info()

<class 'pandas.core.frame.DataFrame'>
Index: 20 entries, 0 to 4
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Cliente          20 non-null     object
 1   Data de venda    20 non-null     object
 2   Valor da compra  20 non-null     float64
dtypes: float64(1), object(2)
memory usage: 1.2+ KB

In [19]:
dados['Cliente'] = dados['Cliente'].astype(str)

In [20]:
dados['Cliente'] = dados['Cliente'].str.upper()

In [21]:
dados['Cliente'] = dados['Cliente'].str.replace('[^a-zA-Z\-\']',' ',regex=True)

<>:1: SyntaxWarning: invalid escape sequence '\-'
<>:1: SyntaxWarning: invalid escape sequence '\-'
/tmp/ipython-input-455926060.py:1: SyntaxWarning: invalid escape sequence '\-'
  dados['Cliente'] = dados['Cliente'].str.replace('[^a-zA-Z\-\']',' ',regex=True)

In [36]:
dados.head(20)

,Cliente,Data de venda,Valor da compra
0,' ANA LUCIA ' 'DIEGO ARMANDIU ' 'DIE...,2022-06-06,836.50
0,' ANA LUCIA ' 'DIEGO ARMANDIU ' 'DIE...,2022-06-06,573.33
0,' ANA LUCIA ' 'DIEGO ARMANDIU ' 'DIE...,2022-06-06,392.80
0,' ANA LUCIA ' 'DIEGO ARMANDIU ' 'DIE...,2022-06-06,512.34
1,'ISABELY JOANES ' 'ISABELY JOANES ' '...,2022-07-06,825.31
1,'ISABELY JOANES ' 'ISABELY JOANES ' '...,2022-07-06,168.07
1,'ISABELY JOANES ' 'ISABELY JOANES ' '...,2022-07-06,339.18
1,'ISABELY JOANES ' 'ISABELY JOANES ' '...,2022-07-06,314.69
2,'ISABELY JOANES ' 'JO O GABRIEL ' 'JU...,2022-08-06,682.05
2,'ISABELY JOANES ' 'JO O GABRIEL ' 'JU...,2022-08-06,386.34
2,'ISABELY JOANES ' 'JO O GABRIEL ' 'JU...,2022-08-06,622.65
2,'ISABELY JOANES ' 'JO O GABRIEL ' 'JU...,2022-08-06,630.79
3,'JULYA MEIRELES ' 'MARIA JULIA ' 'MAR...,2022-09-06,390.30
3,'JULYA MEIRELES ' 'MARIA JULIA ' 'MAR...,2022-09-06,759.16
3,'JULYA MEIRELES ' 'MARIA JULIA ' 'MAR...,2022-09-06,334.47
3,'JULYA MEIRELES ' 'MARIA JULIA ' 'MAR...,2022-09-06,678.78
4,'MARIA JULIA ' 'PEDRO PASCO ' 'PAULO ...,2022-10-06,314.24
4,'MARIA JULIA ' 'PEDRO PASCO ' 'PAULO ...,2022-10-06,311.15
4,'MARIA JULIA ' 'PEDRO PASCO ' 'PAULO ...,2022-10-06,899.16
4,'MARIA JULIA ' 'PEDRO PASCO ' 'PAULO ...,2022-10-06,885.24

In [32]:
dados['Data de venda'] = pd.to_datetime(dados['Data de venda'])

In [33]:
dados.info()

<class 'pandas.core.frame.DataFrame'>
Index: 20 entries, 0 to 4
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Cliente          20 non-null     object
 1   Data de venda    20 non-null     datetime64[ns]
 2   Valor da compra  20 non-null     float64
dtypes: datetime64[ns](1), float64(1), object(1)
memory usage: 1.2+ KB

In [34]:
subset = dados.groupby('Cliente')['Valor da compra'].sum()

In [35]:
subset

Cliente
' ANA  LUCIA    '  'DIEGO ARMANDIU    '  'DIEGO ARMANDIU    '  'DIEGO ARMANDIU    '        2314.97
'ISABELY JOANES    '  'ISABELY JOANES    '  'ISABELY JOANES    '  'ISABELY JOANES    '     1647.25
'ISABELY JOANES    '  'JO O GABRIEL    '  'JULYA MEIRELES    '  'JULYA MEIRELES    '       2321.83
'JULYA MEIRELES    '  'MARIA JULIA    '  'MARIA JULIA    '  'MARIA JULIA    '              2162.71
'MARIA JULIA    '  'PEDRO PASCO    '  'PAULO CASTRO    '  'THIAGO FRITZZ    '              2409.79
Name: Valor da compra, dtype: float64

In [23]:
dados2 = pd.read_json('dados_locacao_imoveis.json')

In [24]:
dados2 = pd.json_normalize(dados2['dados_locacao'])

In [25]:
colunas = list(dados2.columns)
colunas

['apartamento',
 'datas_combinadas_pagamento',
 'datas_de_pagamento',
 'valor_aluguel']

In [26]:
dados2= dados2.explode(colunas[1:])

In [27]:
dados2

,apartamento,datas_combinadas_pagamento,datas_de_pagamento,valor_aluguel
0,A101 (blocoAP),01/06/2022,05/06/2022,"$ 1000,0 reais"
0,A101 (blocoAP),01/07/2022,03/07/2022,"$ 2500,0 reais"
1,A102 (blocoAP),02/06/2022,02/06/2022,"$ 1100,0 reais"
1,A102 (blocoAP),02/07/2022,06/07/2022,"$ 2600,0 reais"
2,B201 (blocoAP),03/06/2022,07/06/2022,"$ 1200,0 reais"
2,B201 (blocoAP),03/07/2022,03/07/2022,"$ 2700,0 reais"
3,B202 (blocoAP),04/06/2022,07/06/2022,"$ 1300,0 reais"
3,B202 (blocoAP),04/07/2022,05/07/2022,"$ 2800,0 reais"
4,C301 (blocoAP),05/06/2022,10/06/2022,"$ 1400,0 reais"
4,C301 (blocoAP),05/07/2022,09/07/2022,"$ 2900,0 reais"
5,C302 (blocoAP),06/06/2022,08/06/2022,"$ 1500,0 reais"
5,C302 (blocoAP),06/07/2022,12/07/2022,"$ 1200,0 reais"
6,D401 (blocoAP),07/06/2022,07/06/2022,"$ 1600,0 reais"
6,D401 (blocoAP),07/07/2022,09/07/2022,"$ 1300,0 reais"
7,D402 (blocoAP),08/06/2022,10/06/2022,"$ 1700,0 reais"
7,D402 (blocoAP),08/07/2022,14/07/2022,"$ 1400,0 reais"
8,E501 (blocoAP),09/06/2022,10/06/2022,"$ 1800,0 reais"
8,E501 (blocoAP),09/07/2022,09/07/2022,"$ 1500,0 reais"
9,E502 (blocoAP),10/06/2022,16/06/2022,"$ 1900,0 reais"
9,E502 (blocoAP),10/07/2022,12/07/2022,"$ 1600,0 reais"
10,F601 (blocoAP),11/06/2022,17/06/2022,"$ 2000,0 reais"
10,F601 (blocoAP),11/07/2022,13/07/2022,"$ 1000,0 reais"
11,F602 (blocoAP),12/06/2022,15/06/2022,"$ 2100,0 reais"
11,F602 (blocoAP),12/07/2022,12/07/2022,"$ 1100,0 reais"
12,G701 (blocoAP),13/06/2022,19/06/2022,"$ 2200,0 reais"
12,G701 (blocoAP),13/07/2022,20/07/2022,"$ 1200,0 reais"
13,G702 (blocoAP),14/06/2022,15/06/2022,"$ 2300,0 reais"
13,G702 (blocoAP),14/07/2022,17/07/2022,"$ 2100,0 reais"
14,H801 (blocoAP),15/06/2022,18/06/2022,"$ 2400,0 reais"
14,H801 (blocoAP),15/07/2022,16/07/2022,"$ 2200,0 reais"

In [28]:
dados2['valor_aluguel'] = dados2['valor_aluguel'].apply(lambda x: x.replace('$', '').replace('reais', '').replace(',','.').strip()).astype(float)

In [29]:
dados2['apartamento'] = dados2['apartamento'].str.replace('\(blocoAP\)', '', regex=True)

<>:1: SyntaxWarning: invalid escape sequence '\('
<>:1: SyntaxWarning: invalid escape sequence '\('
/tmp/ipython-input-2920945497.py:1: SyntaxWarning: invalid escape sequence '\('
  dados2['apartamento'] = dados2['apartamento'].str.replace('\(blocoAP\)', '', regex=True)

In [40]:
dados2

   apartamento datas_combinadas_pagamento datas_de_pagamento  valor_aluguel
0        A101                  01/06/2022         05/06/2022         1000.0
0        A101                  01/07/2022         03/07/2022         2500.0
1        A102                  02/06/2022         02/06/2022         1100.0
1        A102                  02/07/2022         06/07/2022         2600.0
2        B201                  03/06/2022         07/06/2022         1200.0
2        B201                  03/07/2022         03/07/2022         2700.0
3        B202                  04/06/2022         07/06/2022         1300.0
3        B202                  04/07/2022         05/07/2022         2800.0
4        C301                  05/06/2022         10/06/2022         1400.0
4        C301                  05/07/2022         09/07/2022         2900.0
5        C302                  06/06/2022         08/06/2022         1500.0
5        C302                  06/07/2022         12/07/2022         1200.0
6        D401                  07/06/2022         07/06/2022         1600.0
6        D401                  07/07/2022         09/07/2022         1300.0
7        D402                  08/06/2022         10/06/2022         1700.0
7        D402                  08/07/2022         14/07/2022         1400.0
8        E501                  09/06/2022         10/06/2022         1800.0
8        E501                  09/07/2022         09/07/2022         1500.0
9        E502                  10/06/2022         16/06/2022         1900.0
9        E502                  10/07/2022         12/07/2022         1600.0
10       F601                  11/06/2022         17/06/2022         2000.0
10       F601                  11/07/2022         13/07/2022         1000.0
11       F602                  12/06/2022         15/06/2022         2100.0
11       F602                  12/07/2022         12/07/2022         1100.0
12       G701                  13/06/2022         19/06/2022         2200.0
12       G701                  13/07/2022         20/07/2022         1200.0
13       G702                  14/06/2022         15/06/2022         2300.0
13       G702                  14/07/2022         17/07/2022         2100.0
14       H801                  15/06/2022         18/06/2022         2400.0
14       H801                  15/07/2022         16/07/2022         2200.0

In [41]:
dados2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 30 entries, 0 to 14
Data columns (total 4 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   apartamento                 30 non-null     object
 1   datas_combinadas_pagamento  30 non-null     object
 2   datas_de_pagamento          30 non-null     object
 3   valor_aluguel               30 non-null     float64
dtypes: float64(1), object(3)
memory usage: 1.2+ KB

In [46]:
dados2['datas_de_pagamento'] = pd.to_datetime(dados2['datas_de_pagamento'], format='%d/%m/%Y')

In [47]:
dados2['datas_combinadas_pagamento'] = pd.to_datetime(dados2['datas_combinadas_pagamento'], format='%d/%m/%Y')

In [48]:
dados2['atraso'] = dados2['datas_combinadas_pagamento'] - dados2['datas_de_pagamento']

In [49]:
dados2

,apartamento,datas_combinadas_pagamento,datas_de_pagamento,valor_aluguel,atraso
0,A101,2022-06-01,2022-06-05,1000.0,-4 days
0,A101,2022-07-01,2022-07-03,2500.0,-2 days
1,A102,2022-06-02,2022-06-02,1100.0,0 days
1,A102,2022-07-02,2022-07-06,2600.0,-4 days
2,B201,2022-06-03,2022-06-07,1200.0,-4 days
2,B201,2022-07-03,2022-07-03,2700.0,0 days
3,B202,2022-06-04,2022-06-07,1300.0,-3 days
3,B202,2022-07-04,2022-07-05,2800.0,-1 days
4,C301,2022-06-05,2022-06-10,1400.0,-5 days
4,C301,2022-07-05,2022-07-09,2900.0,-4 days
5,C302,2022-06-06,2022-06-08,1500.0,-2 days
5,C302,2022-07-06,2022-07-12,1200.0,-6 days
6,D401,2022-06-07,2022-06-07,1600.0,0 days
6,D401,2022-07-07,2022-07-09,1300.0,-2 days
7,D402,2022-06-08,2022-06-10,1700.0,-2 days
7,D402,2022-07-08,2022-07-14,1400.0,-6 days
8,E501,2022-06-09,2022-06-10,1800.0,-1 days
8,E501,2022-07-09,2022-07-09,1500.0,0 days
9,E502,2022-06-10,2022-06-16,1900.0,-6 days
9,E502,2022-07-10,2022-07-12,1600.0,-2 days
10,F601,2022-06-11,2022-06-17,2000.0,-6 days
10,F601,2022-07-11,2022-07-13,1000.0,-2 days
11,F602,2022-06-12,2022-06-15,2100.0,-3 days
11,F602,2022-07-12,2022-07-12,1100.0,0 days
12,G701,2022-06-13,2022-06-19,2200.0,-6 days
12,G701,2022-07-13,2022-07-20,1200.0,-7 days
13,G702,2022-06-14,2022-06-15,2300.0,-1 days
13,G702,2022-07-14,2022-07-17,2100.0,-3 days
14,H801,2022-06-15,2022-06-18,2400.0,-3 days
14,H801,2022-07-15,2022-07-16,2200.0,-1 days

In [51]:
media_atraso = dados2.groupby(['apartamento'])['atraso'].mean()

In [52]:
media_atraso

apartamento
A101    -3 days +00:00:00
A102    -2 days +00:00:00
B201    -2 days +00:00:00
B202    -2 days +00:00:00
C301    -5 days +12:00:00
C302    -4 days +00:00:00
D401    -1 days +00:00:00
D402    -4 days +00:00:00
E501    -1 days +12:00:00
E502    -4 days +00:00:00
F601    -4 days +00:00:00
F602    -2 days +12:00:00
G701    -7 days +12:00:00
G702    -2 days +00:00:00
H801    -2 days +00:00:00
Name: atraso, dtype: timedelta64[ns]